---
title: "Untitled"
format: html
editor: visual
---

**\# Применение средств и методов OSINT**

\
**\## Цель работы**\
1. Освоить базовые подходы процессов OSINT2. Освоить современные инструменты поиска и сбора информации3. Освоить инструменты совместной работы в ходе аналитической деятельности\
**\### План выполнения**\
1. Собрать информацию о профильных компаниях в сфере ИБ и их продуктах2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.4. Сформировать представление о рынке отечественных решений ИБ\
**\### Ход работы**\
Собрать публичную информацию об компании Kaspersky\
1. Полное название компанииАО "Лаборато́рия Касперского" --- международная компания, специализирующаяся на разработке систем защиты от компьютерных вирусов, спама, хакерских атак и прочих киберугроз.2. Структура компании:\
Компания строится по матричному принципу, созданы программно-целевые группы во главе с руководителем проекта, которые подчиняются высшему руководству компании.\
3. Основные направления деятельности компании\
3.1 услуги\
\
\~ Информирование\
- информация об угрозах- анализ уязвимостей\
\~ Подготовка\
- повышение осведомленности- тренинги специалистов\
\~ Реагирование\
- обнаружение кибератак- расследование инцидентов- консультации по запросу\
\~ Трансформация\
- оценка кибербезопасности продуктов и решений- анализ информационной безопасности\
3.2 производимые продукты, основные сферы их применения, их достоинства\
Основная сфера применения - это безопасность в цифровом мире.Производимые продукты для дома:Совместимость с Windows, macOS, Android, iOS.\
1. Kaspersky Standart - это стандартная защитаплюсы:\
+ Защита от вирусов, вредоносного ПО и программ-вымогателей+ Безопасный просмотр веб-сайтов+ Ликвидация существующих вредоносных программ+ Анти-Фишинг+ Двусторонний сетевой экран+ Оптимизация производительности+ Освобождение места на устройстве+ Управление приложениями+ Защита онлайн-платежей+ Обнаружение сталкерских приложений\
2. Kaspersky Plus - это расширенная защита, в его достоинтсва входит все, что и в Kaspersky Standart и добовляется еще немного:\
+ Защита от криптоугроз+ Диагностика жесткого диска+ Поиск утечек данных+ Определитель номера Who Calls+ Менеджер паролей+ Проверка безопасности паролей\
3. Kaspersky Premium - это максимальная защита, в его достоинства входит все, что и в Kaspersky Plus и добовляется еще немного:\
+ Безопасное хранилище личных документов+ Обнаружение удаленного доступа+ Мониторинг Умного дома+ Круглосуточная удаленная поддержка+ Обнаружение и удаление вирусов силами экспертов+ Проверка работоспособности компьютера экспертами\
Так же компания производит продукты для бизнеса и их довольно много с ними можно ознакомиться на сайте: https://www.kaspersky.ru\
3.3 используемые технологии, языки программированияТехнологии обеспечения безопасности:\
- Машинное обучение в кибербезопасности- Передовая защита от целевых атак- Защита на основе поведенческиго анализа- Защита от бесфайловых угроз- Big Data: технология Astraea- Выявление и обезвредивание руткитов- Облачный мониторинг угроз\
Языки программирования: C++, C#, Nemerle\
4. Основные клиенты компании:\
Продукты и технологии «Лаборатории Касперского» защищают более 400 млн. пользователей по всему миру. Количество корпоративных клиентов компании превышает 270 тыс. компаний, среди которых крупные государственные и коммерческие организации (например, BASF, Siemens, ВГТРК, Департамент информационных технологий города Москвы, РЖД, Росгосстрах, Министерство внутренних дел, Министерство обороны, Высший Арбитражный Суд, Федеральная налоговая служба, Фонд социального страхования, Счетная палата, и многие другие), а также предприятия малого и среднего бизнеса, лечебные и образовательные учреждения по всему миру.\
5. Основные веб-сайты компании и ее продуктов:\
Основной веб-сайтhttps://www.kaspersky.ru\
6. Публичные сотрудники компании, активные участники ИТ и ИБ-сообщества, участники профильных конференций:\
https://www.kaspersky.ru/about/team \
На этом сайте можно найти можно найти основных сотрудников компании и прочитать дополнительную информации о человеке и узнать его непосредственную роль в компании, таких как:\
Генеральный директор - Евгений КасперскийИсполнительный директор - Андрей ТихоновДиректор по исследованиям и разработке - Антон Иванов и так далее.\
7. Уникальные достижения, ключевые продукты компании (при наличии)\
С наградами можно ознакомиться на сайте:https://www.kaspersky.ru/blog/awards-post/19601\
Компания выпускает решения для защиты всех типов сетевых узлов. Помимо продуктов, разработанных для защиты отдельных узлов сети, Лаборатория Касперского предлагает комплексные решения, например, Kaspersky Total  Security для бизнеса.\
**\### Оценка результата**\
В результате данной практической работы мы выяснили, что Kaspersky - это одна из ведещих компаний по разрабатыванию антивирусного ПО, с множеством продуктов, подходящих как для дома, так и для бизнеса.\
**\### Вывод**\
Освоили базовые подходы процессов OSIN, современные инструменты поиска и сбора информации.
